---
 apiVersion: apps/v1beta2
 kind: Deployment
 metadata:
   name: hello-world
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: hello-world
   template:
     metadata:
       labels:
         app: hello-world
     spec:
       imagePullSecrets:
         - name: regcred
       containers:
         - name: hello-world
           image: csriman09/hello-world
           ports:
             - containerPort: 7002
