---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  annotations:
    flux.weave.works/automated_msg: test
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: csriman09/nginx:d03dbfc
        ports:
        - containerPort: 80
